### ISSUE TITLE
Getting a spam error that severely lags my game

### ISSUE THREAD

**Issue by haydenhayden011** [Matt-Wild/faithful#1]
![image](https://github.com/user-attachments/assets/17abbb4e-47bc-426e-98b2-f225a4406bfb)
[zipped_log (2).zip](https://github.com/user-attachments/files/18000423/zipped_log.2.zip)

Theres a pic of the error I was getting. It is gone the moment I remove the mod. Log attached

**Comment by Matt-Wild** [comment]
This issue should be resolved as of v1.0.5

**Comment by Matt-Wild** [comment]
This issue should be resolved as of v1.0.5
