### ISSUE TITLE
Not showing full Item Description when using LookingGlass

### ISSUE THREAD

**Issue by Morpok** [Matt-Wild/faithful#3]
I'm not sure if this is something LookingGlass needs to fix or if you can fix it. But when I'm using LookingGlass, hovering over the item in my inventory doesn't display the full item descriptions. I also tried an alternative with HUDdleUP and the problem persisted.

![Description2](https://github.com/user-attachments/assets/4aebb0e3-0e77-48fa-b66d-3fc1e43f62fe)
![Description1](https://github.com/user-attachments/assets/e502aaa6-76f5-4c6b-b619-c5ba2ddea0ee)

**Comment by Matt-Wild** [comment]
I'm not sure if this issue was closed due to an update with LookingGlass, but if anyone else if experiencing this issue there are options within the mod's config to enable the full item descriptions.
